### ISSUE TITLE
Stacking children

### ISSUE THREAD

**Issue by mshd** [ogroppo/entitree#117]
I know it's probably impossible but it would be so great to have this feature

**Comment by ogroppo** [comment]
Could you provide a sketch?

**Comment by mshd** [comment]
I think the bigger problem is that trees tend to increase in size. Stacking will improve the space management. TreantJS was able to do it. But I know it's more tricky with React
![Screenshot from 2020-10-19 22-43-30](https://user-images.githubusercontent.com/17379661/96509667-a9cce200-125c-11eb-9f49-5f916b118afb.png)
https://dataprick.github.io/wikitree/public/?q=Q9682&level=5&type=descendants&orientation=North&lang=en

**Comment by ogroppo** [comment]
it has nothing to do with react, you need to build the object differently and pass it to the d3-hierarchy algo that calculates the positions, so technically this could be achieved perhaps setting the sibling as a child of the previous one, then apply an extra property like `_isStackedSibling` so that the connection shape makes that `L`

**Comment by mshd** [comment]
Waiting for https://github.com/d3/d3-hierarchy/pull/173

**Comment by mshd** [comment]
With new compact themes, this issue has become less important
